[package]
name = "server"
version = "0.1.0"
authors = ["boxdot <d@zerovolt.org>"]
edition = "2021"
publish = false

[[bin]]
name = "server"
path = "src/server.rs"

[[bin]]
name = "client"
path = "src/client.rs"

[dependencies]
tonic-ws-transport = { path = "../../transport", features = [] }
tonic = { version = "0.14.1", features = ["transport", "codegen"] }
tonic-prost = "0.14.2"
prost = "0.14.1"
tokio = { version = "1.1.1", features = ["full"] }
futures-util = "0.3.12"
tokio-tungstenite = "0.23"
tokio-stream = { version = "0.1.2", features = ["net"] }
hyper-util = "0.1.5"

[build-dependencies]
tonic-prost-build = "0.14.1"
